name: Build
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  api:
    name: Build Client with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15, 1.14, 1.13]

    steps:
    - uses: actions/checkout@v1
    - name: Set go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build client
      run: |
        go build ./pkg/client
